# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: Ocean
day_night: true
font: Classic
font_size: m

# SEO

site_type: Organization
local_business_type: ''
org_name: ''
description: My research group description.
twitter: ''

# Contact (edit or remove options as required)

email: test@example.org
phone: 888 888 88 88
address:
  street: 83 Tat Chee Ave
  city: Kowloon Tong
  country: Hong Kong
  country_code: HK
coordinates:
  latitude: '22.337274727624777'
  longitude: '114.1724234'

contact_links:
#  - icon: comments
#    icon_pack: fas
#    name: Discuss on Forum
#    link: 'https://www.cityu.edu.hk'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: false

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: false
math: false
diagram: false
privacy_pack: false
show_related:
  post: true
  project: true
  publication: true
  talk: true
reading_time: true
section_pager: false
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
comments:
  provider: ''
  commentable:
    page: true
    post: true
    docs: true
    project: true
    publication: true
    talk: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider:
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: main
  local_backend: false
icon:
  pack:
    ai: true
